import { execSync, execFileSync } from 'child_process';
import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { randomUUID } from 'crypto';
import type { MaterialProfile } from '../types/pipeline.js';

interface SlicerPath {
  binary: string;
  name: string;
}

export interface SlicerResult {
  success: boolean;
  slicerName: string | null;
  gcodePath?: string;
  errors: string[];
  warnings: string[];
  metrics: {
    filamentUsedGrams: number;
    printTimeMinutes: number;
    totalLayers: number;
    firstLayerHeight: number;
  } | null;
}

function findSlicers(): SlicerPath[] {
  const candidates: SlicerPath[] = [];
  const check = (bin: string, name: string) => {
    try { execSync(`which ${bin} 2>/dev/null`, { timeout: 3000 }); candidates.push({ binary: bin, name }); } catch { /* not found */ }
  };
  check('prusa-slicer', 'prusaslicer');
  check('PrusaSlicer', 'prusaslicer');
  check('prusaslicer', 'prusaslicer');
  check('bambu-cli', 'bambustudio');
  check('bambu-studio', 'bambustudio');
  check('orca-slicer', 'orcaslicer');
  return candidates;
}

export async function sliceStl(
  stlPath: string,
  material: MaterialProfile,
): Promise<SlicerResult> {
  const slicers = findSlicers();
  if (slicers.length === 0) {
    return {
      success: true,
      slicerName: null,
      errors: [],
      warnings: [],
      metrics: null,
    };
  }

  for (const slicer of slicers) {
    const result = await trySlice(slicer, stlPath, material);
    if (result.success || result.errors.length > 0) {
      return result;
    }
  }

  return {
    success: true,
    slicerName: null,
    errors: [],
    warnings: [],
    metrics: null,
  };
}

async function trySlice(
  slicer: SlicerPath,
  stlPath: string,
  material: MaterialProfile,
): Promise<SlicerResult> {
  const workDir = join(tmpdir(), `slicer_${randomUUID()}`);
  mkdirSync(workDir, { recursive: true });

  const configPath = writeSlicerConfig(workDir, material);
  const gcodePath = join(workDir, 'output.gcode');

  try {
    const args = [
      '--export-gcode',
      '--output', gcodePath,
      '--load', configPath,
      '--center', '125', '105',
      stlPath,
    ];

    execFileSync(slicer.binary, args, {
      timeout: 60000,
      encoding: 'utf-8',
      stdio: 'pipe',
    });

    if (!existsSync(gcodePath)) {
      return {
        success: false,
        slicerName: slicer.name,
        errors: ['Slicer completed but no G-code was produced.'],
        warnings: [],
        metrics: null,
      };
    }

    const metrics = parseGcodeMetrics(gcodePath);
    const warnings = analyzeGcodeWarnings(gcodePath, material);

    return {
      success: true,
      slicerName: slicer.name,
      gcodePath,
      errors: [],
      warnings,
      metrics,
    };
  } catch (err: any) {
    const stderr = err?.stderr?.toString() ?? err?.message ?? '';
    const errorLines = stderr.split('\n').filter((l: string) =>
      l.includes('error') || l.includes('fail') || l.includes('Error') || l.includes('FATAL'),
    );

    return {
      success: false,
      slicerName: slicer.name,
      errors: errorLines.length > 0
        ? errorLines.slice(0, 5).map((l: string) => `SLICER_ERROR: ${l.trim()}`)
        : [`SLICER_ERROR: ${stderr.trim().slice(0, 200)}`],
      warnings: [],
      metrics: null,
    };
  }
}

function writeSlicerConfig(workDir: string, material: MaterialProfile): string {
  const configPath = join(workDir, 'config.ini');

  const bedTemp = material.bedTempC >= 45 ? material.bedTempC : 60;
  const firstLayerTemp = material.nozzleTempC + 5;
  const bedType = material.buildPlateAdhesion === 'textured_pei' ? 'Textured PEI Plate'
    : material.buildPlateAdhesion === 'smooth_pei' ? 'Smooth PEI Plate'
    : material.buildPlateAdhesion === 'engineering' ? 'Engineering Plate'
    : 'Cool Plate';

  const config = `# Auto-generated by automech
[print:automech_${material.id}]
inherit = 0.20mm Standard
filament_settings_id = automech_${material.id}
printer_settings_id = Bambu Lab P1S 0.4 nozzle
[filament:automech_${material.id}]
first_layer_temperature = ${firstLayerTemp}
temperature = ${material.nozzleTempC}
bed_temperature = ${bedTemp}
first_layer_bed_temperature = ${bedTemp + 5}
fan_always_on = 1
cooling = 1
min_print_speed = 10
max_volumetric_speed = 12
filament_density = ${material.densityGcm3}
filament_type = ${material.id.toUpperCase()}
[printer:Bambu Lab P1S 0.4 nozzle]
printer_model = P1S
printer_technology = FFF
bed_shape = 0x0,256x0,256x256,0x256
bed_custom_texture = ${bedType}
bed_custom_model = ${bedType}
`;

  writeFileSync(configPath, config, 'utf-8');
  return configPath;
}

function parseGcodeMetrics(gcodePath: string): SlicerResult['metrics'] {
  try {
    const content = readFileSync(gcodePath, 'utf-8');
    const lines = content.split('\n');

    let filamentUsed = 0;
    let printTime = 0;
    let totalLayers = 0;
    let firstLayerH = 0;

    for (const line of lines) {
      if (line.startsWith('; filament used [g] = ')) {
        filamentUsed = parseFloat(line.split('=')[1].trim());
      }
      if (line.startsWith('; estimated printing time')) {
        const match = line.match(/(\d+)h\s*(\d+)m/);
        if (match) printTime = parseInt(match[1]) * 60 + parseInt(match[2]);
      }
      if (line.startsWith('; total layers count = ')) {
        totalLayers = parseInt(line.split('=')[1].trim());
      }
      if (line.startsWith('; first_layer_print_min = ') && firstLayerH === 0) {
        const idx = content.indexOf('; first_layer_height = ');
        if (idx >= 0) {
          firstLayerH = parseFloat(content.slice(idx + 24).split('\n')[0].trim());
        }
      }
    }

    if (filamentUsed === 0 && printTime === 0 && totalLayers === 0) {
      return null;
    }

    return {
      filamentUsedGrams: filamentUsed,
      printTimeMinutes: printTime,
      totalLayers,
      firstLayerHeight: firstLayerH,
    };
  } catch {
    return null;
  }
}

function analyzeGcodeWarnings(gcodePath: string, material: MaterialProfile): string[] {
  const warnings: string[] = [];
  try {
    const content = readFileSync(gcodePath, 'utf-8');
    const lower = content.toLowerCase();

    if (lower.includes('overhang perimeters') || lower.includes('bridge')) {
      warnings.push('SLICER_WARNING: Overhang/bridging issues detected — may need support material.');
    }

    const smallPerimeterMatch = content.match(/; small perimeters.*?(\d+)/);
    if (smallPerimeterMatch && parseInt(smallPerimeterMatch[1]) > 20) {
      warnings.push(`SLICER_INFO: ${smallPerimeterMatch[1]} small perimeter sections — check for fine features.`);
    }

  } catch {
    // best effort
  }
  return warnings;
}
